stages:
  - test

variables:
  GIT_DEPTH: 10
  ANDROID_IMAGE: alpine-android:android-33-jdk17

.gradle_cache:
  before_script:
    - >
      if [ $CI_SHARED_ENVIRONMENT ]; then
        export GRADLE_USER_HOME="$HOME/.gradle"
      else
        export GRADLE_USER_HOME="`pwd`/.gradle"
        mkdir -p $GRADLE_USER_HOME
      fi
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches

unit_tests:
  extends: .gradle_cache
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(feature|issue)\/.*/'
  artifacts:
    when: always # Also uploads the report when tests fail
    reports:
      junit:
        - "**/build/test-results/testReleaseUnitTest/*.xml"
        - "**/build/test-results/test/*.xml"
  script:
    - ./gradlew test